const { Router } = require("express")
const authController = require("../controllers/authController")
const passport = require("passport")
const checkAuth = require("../middleware/isAuthenticated")
const routes = Router()

routes.post("/register", authController.register)
// routes.post("/login", passport.authenticate('local', {}), authController.login)
routes.post("/login", authController.login)
routes.get("/logout", checkAuth, authController.logout)
routes.get("/load_user", checkAuth, authController.loadUser)
routes.post("/update_user", checkAuth, authController.updateUser)
routes.post("/upload_photo", checkAuth, authController.uploadPhoto)
routes.get("/search", checkAuth, authController.searchUsers)
module.exports = routes 